let number1 = 1;
let number2 = 2;
const product = number1 * number2;
console.log(product, typeof product);
let charge = 50;
let payment = 42;
const amountRemaining = payment - charge;
console.log(amountRemaining, typeof amountRemaining);
let tests = 80;
let assignments = 85;
let final = 75;
const grade = (tests + assignments + final) / 3;
console.log(grade, typeof grade);
const firstName = 'Duncan';
const lastName = 'Harrison';
let fullName = firstName + ' ' + lastName;
console.log(fullName, typeof fullName);
let pH = 6.9;
const isAcidic = pH < 7;
console.log(isAcidic, typeof isAcidic);
let numberOfSoldiers = 301;
const isSparta = numberOfSoldiers === 300;
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT';
console.log(nickname, typeof nickname);
